---
title: "Материалы"
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    theme: united
---
# Регрессионный анализ: продолжение, 2024
 
### Обозначения
 
`r  shiny::icon("scroll")` -- презентация / конспект занятия / семинарский листочек
 
`r  shiny::icon("readme")` -- Reading
 
`r  shiny::icon("desktop")` -- материалы для практикума (данные, код)
 
`r  shiny::icon("pencil")` -- задание 
 
## Занятие 1
 
Тема: О чем курс и каковы правила игры? Повторение: парная линейная регрессия
  
`r  shiny::icon("scroll")` <a href="polit_reg_intro_2024.pdf" title=>Презентация-введение</a> 

`r  shiny::icon("scroll")` <a href="OLS_1.pdf" title=>МНК-оценки: случай парной линейной регрессии</a> 

`r  shiny::icon("scroll")` <a href="reg_seminar1.pdf" title=>Семинар 1</a> 

`r  shiny::icon("scroll")` <a href="reg_hw1_2024.pdf" title=>Домашнее задание 1</a> 

## Занятие 2
 
Тема: парная линейная регрессия; множественная линейная регрессия: спецификация, выведение формулы для получения оценок коэффициентов, допущения относительно ошибок

`r  shiny::icon("desktop")` <a href="reg_lab1_2024.ipynb" title=>Практикум 1</a> 

`r  shiny::icon("desktop")` <a href="lab1.dta" title=>Данные к практикуму 1</a> 
  
`r  shiny::icon("scroll")` <a href="reg_seminar2_2024.pdf" title=>Семинар 2</a> 

`r  shiny::icon("scroll")` <a href="reg_hw2_2024.pdf" title=>Домашнее задание 2</a> 

`r  shiny::icon("scroll")` <a href="reg_hw2_solution_.pdf" title=>Решение домашнего задания 2</a> 

## Занятие 3
 
Тема: множественная линейная регрессия: спецификация

`r  shiny::icon("scroll")` <a href="reg_backdoor.pdf" title=>Выбор контрольных переменных</a> 

`r  shiny::icon("scroll")` <a href="reg_interaction_presentation.pdf" title=>Презентация: переменные взаимодействия</a> 

`r  shiny::icon("scroll")` <a href="reg_seminar3.pdf" title=>Семинар 3</a> 

`r  shiny::icon("scroll")` <a href="reg_interactions_solution.pdf" title=>Решение семинарских заданий</a> 


Домашнее задание: 

`r  shiny::icon("readme")` <a href="https://disk.yandex.ru/i/XhNnotShTyC8dw" title=> Brambor et al.</a>
 
`r  shiny::icon("readme")` <a href="https://disk.yandex.ru/i/ufuj_2Ks2FglpQ" title=> Franzese, Kam, pp. 19 - 39 </a>

Подготовиться к проверочной работе 1


## Занятие 4
 
Тема: переменные взаимодействия (практикум), мультиколлинеарность 

`r  shiny::icon("desktop")` <a href="reg_lab2_2024.ipynb" title=>Практикум 2</a>

## Занятие 5
 
Тема: метод главных компонент (в контексте работы с мультиколлинеарностью), гребневая регрессия 

`r  shiny::icon("desktop")` <a href="reg_lab3_1_2024_.ipynb" title=>Практикум 3 (1) </a>

`r  shiny::icon("desktop")` <a href="reg_lab3_2_2024_.ipynb" title=>Практикум 3 (2) </a>

`r  shiny::icon("desktop")` <a href="lab3_2.dta" title=>Данные к практикуму 3 (2) </a>

`r  shiny::icon("scroll")` <a href="PCA_lecture.pdf" title=>МГК презентация</a> 

## Занятие 6
 
Тема: гетероскедастичность 

## Занятие 7
 
Тема: гетероскедастичность, нетипичные наблюдения 

`r  shiny::icon("scroll")` <a href="reg_seminar_solution.pdf" title=>Семинарский лист с решением</a> 

`r  shiny::icon("desktop")` <a href="reg_lab4_2024.ipynb" title=> Практикум 4</a>

## Занятие 8
 
Тема: подготовка к контрольной работе 

`r  shiny::icon("scroll")` <a href="reg_practice.pdf" title=> Задачи для тренировки </a> 

## Занятие 9
 
Тема: контрольная работа; эндогенность в регрессионной модели: введение

`r  shiny::icon("scroll")` <a href="reg_endogeneity_intro.pdf" title=>Эндогенность: введение</a> 

`r  shiny::icon("scroll")` <a href="reg_causalinference.pdf" title=>Каузальный вывод. Базовые понятия</a> 


## Занятие 10
 
Тема: метод DiD

`r  shiny::icon("scroll")` <a href="DiD_lecture.pdf" title=>Метод DiD</a> 

`r  shiny::icon("desktop")` <a href="reg_lab5_2024.ipynb" title=> Практикум 5</a>

`r  shiny::icon("desktop")` <a href="DiDdata.dta" title=> DiDdata</a>

`r  shiny::icon("scroll")` <a href="reg_seminar5_2024_.pdf" title=>Семинарский лист 5</a> 


## Занятие 11
 
Тема: меры качества модели, кросс-валидация, информационные критерии, тесты для сравнения вложенных моделей

`r  shiny::icon("desktop")` <a href="reg_lab6_2024_.ipynb" title=> Практикум 6</a>


# Регрессионный анализ: панельные данные и каузальность, 2025
 
### Обозначения
 
`r  shiny::icon("scroll")` -- презентация / конспект занятия / семинарский листочек
 
`r  shiny::icon("readme")` -- Reading
 
`r  shiny::icon("desktop")` -- материалы для практикума (данные, код)
 
`r  shiny::icon("pencil")` -- задание 

## Занятие 1
 
Тема: О чем курс и каковы правила игры? Введение в модели с фиксированными эффектами
  
`r  shiny::icon("scroll")` <a href="RAPDC_intro_2025.pdf" title=>Презентация-введение</a> 

`r  shiny::icon("scroll")` <a href="RAPDC_lecture1.html" title=>Занятие 1. Конспект</a> 

`r  shiny::icon("scroll")` <a href="RAPDC_seminar1_2025.pdf" title=>Семинар 1</a> 

Домашнее задание:

`r  shiny::icon("readme")`  <a href="https://disk.yandex.ru/i/G9DO5ZMwYmP2Mw" title=>Stock, Watson, Chapter 10 (10.1 - 10.3)</a>  
 
Решить Задачу 2 из <a href="RAPDC_seminar1_2025.pdf" title=>Семинарского листка 1</a> 

## Занятие 2
 
Тема: Модели с фиксированными эффектами (продолжение)
  
`r  shiny::icon("scroll")` <a href="RAPDC_lecture2.html" title=>Занятие 2. Конспект</a> 

## Занятие 3
 
Тема: Модели с фиксированными эффектами VS модели со случайными эффектами
  
`r  shiny::icon("scroll")` <a href="RAPDC_lecture3.html" title=>Занятие 3. Конспект</a> 

Домашнее задание: 
 
`r  shiny::icon("readme")`  <a href="https://disk.yandex.ru/i/V6oQg2xZeysiDg" title=>Kropko, Kubinec, 2020</a>  
 
Вопросы к статье:
 
1) Приведите примеры содержательных вопросов, на которые могут помочь ответить модели с FE на пространственные единицы; с FE на временные периоды.
 
2) Как реализуется внутригрупповое преобразование в FE-моделях на пространственные единицы? А в случае если модель с FE на временные периоды? 
 
3) В чем отличие интерпретации оценок коэффициентов при предикторах в моделях с FE на пространственные единицы по сравнению с соответствующей интерпретацией в моделях с FE на временные периоды?  
 
4) Как устроена twoways FE-model? В чем ограничения такой модели? Почему ее нередко называют tricky model? 

## Занятие 4
 
Тема: Проверочная работа. Введение в модели со смешанными эффектами

## Занятие 5
 
Тема: Модели со смешанными эффектами (продолжение)

`r  shiny::icon("scroll")` <a href="RAPDC_ME.html" title=>Занятие 5. Конспект</a> 

`r  shiny::icon("scroll")` <a href="RAPDC_ME.pdf" title=>Презентация. Введение в ME-модели</a> 

## Занятие 6
 
Тема: адаптация моделей со смешанными эффектами применительно к анализу панельных данных

`r  shiny::icon("scroll")` <a href="RAPDC_ME_panel.pdf" title=>Презентация </a> 

## Занятие 7 

Тема: автокорреляция. Введение в динамические модели (модели с лагированными переменными)







